```
RuntimeError: User specified an unsupported autocast device_type 'mps'
```

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/conda/cli/main.py", line 78, in main_subshell
        exit_code = do_call(args, parser)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 166, in do_call
        result = getattr(module, func_name)(args, parser)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/conda/notices/core.py", line 124, in wrapper
        return func(*args, **kwargs)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/conda/cli/main_install.py", line 26, in execute
        install(args, parser, "install")
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/conda/cli/install.py", line 320, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/conda/core/solve.py", line 139, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/conda/core/solve.py", line 200, in solve_for_diff
        final_precs = self.solve_final_state(
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/conda/core/solve.py", line 345, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/conda/common/io.py", line 85, in decorated
        return f(*args, **kwds)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/conda/core/solve.py", line 565, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/conda/core/solve.py", line 1280, in _prepare
        reduced_index = get_reduced_index(
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/conda/core/index.py", line 267, in get_reduced_index
        new_records = SubdirData.query_all(
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/conda/core/subdir_data.py", line 165, in query_all
        result = tuple(
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
        yield fs.pop().result()
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/concurrent/futures/_base.py", line 446, in result
        return self.__get_result()
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
        raise self._exception
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/conda/core/subdir_data.py", line 150, in subdir_query
        return tuple(
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/conda/core/subdir_data.py", line 172, in query
        self.load()
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/conda/core/subdir_data.py", line 272, in load
        _internal_state = self._load()
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/conda/core/subdir_data.py", line 315, in _load
        repodata, state = fetcher.fetch_latest_parsed()
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/conda/gateways/repodata/__init__.py", line 718, in fetch_latest_parsed
        return json.loads(parsed), state
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/json/decoder.py", line 353, in raw_decode
        obj, end = self.scan_once(s, idx)
    json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 26214395 (char 26214394)

`$ /opt/homebrew/Caskroom/miniconda/base/bin/conda install pytorch torchvision torchaudio -c pytorch-nightly`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/opt/homebrew/Caskroom/miniconda/base/bin/conda
             CONDA_PREFIX=/opt/homebrew/Caskroom/miniconda/base
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/opt/homebrew/Caskroom/miniconda/base/bin/python
               CONDA_ROOT=/opt/homebrew/Caskroom/miniconda/base
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 INFOPATH=/opt/homebrew/share/info:/opt/homebrew/share/info:
               LD_PRELOAD=<not set>
                  MANPATH=/opt/homebrew/share/man:/usr/share/man:/usr/local/share/man:/opt/X11/s
                          hare/man:/opt/homebrew/share/man::
                     PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/
                          App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion
                          Tech Preview.app/Contents/Public:/opt/X11/bin:/Library/Apple/usr/bin:/
                          opt/homebrew/Caskroom/miniconda/base/bin:/opt/homebrew/Caskroom/minico
                          nda/base/condabin:/opt/homebrew/bin:/opt/homebrew/sbin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /opt/homebrew/Caskroom/miniconda/base
            shell level : 1
       user config file : /Users/yaroslav/.condarc
 populated config files : /Users/yaroslav/.condarc
          conda version : 23.9.0
    conda-build version : 3.28.4
         python version : 3.9.18.final.0
       virtual packages : __archspec=1=m2
                          __osx=13.0=0
                          __unix=0=0
       base environment : /opt/homebrew/Caskroom/miniconda/base  (writable)
      conda av data dir : /opt/homebrew/Caskroom/miniconda/base/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/pytorch-nightly/osx-arm64
                          https://conda.anaconda.org/pytorch-nightly/noarch
                          https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/homebrew/Caskroom/miniconda/base/pkgs
                          /Users/yaroslav/.conda/pkgs
       envs directories : /opt/homebrew/Caskroom/miniconda/base/envs
                          /Users/yaroslav/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.9.0 requests/2.31.0 CPython/3.9.18 Darwin/22.1.0 OSX/13.0
                UID:GID : 501:20
             netrc file : /Users/yaroslav/.netrc
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: 
Timeout reached. No report sent.